### ISSUE TITLE
only vanilla mob heads render shaders with Just Mob Heads

### ISSUE THREAD

**Issue by steve-the-player** [A11v1r15/Skull_vision#1]
I'm using [Just Mob Heads by Serilium](https://modrinth.com/mod/just-mob-heads), which functions similarly to the vanillatweaks mob head datapack, but the heads it generates don't play mob sounds when placed on a noteblock. According to your datapack file at `/src/main/resources/assets/data/minecraft/tags/items/noteblock_top_instruments.json`, only mob heads which have been added to that category and play sounds when the head is placed on top of a noteblock will generate mob head shaders.

**Comment by A11v1r15** [comment]
I'm still deciding what I should do in regard to this. I'd rather have Serilium to fix their mod, since it would also make it a better mod and it already has it as an [issue](https://github.com/ricksouth/serilum-mc-mods/issues/1434#issue-1462774920)

**Comment by steve-the-player** [comment]
Ah. Well, in the meantime, do you have any other mobhead datapacks/mods you can recommend? I've tried Headed, but it has multiple known issues where the game crashes or freezes, and also doesn't appear to add the noteblock_top_instruments tag (oh wait, I just noticed, you were the one that submitted that bug report, heh)

**Comment by A11v1r15** [comment]
Unfortunately, I only know of these 3 (Serilium's, headed and vanilla tweaks'), if you find more of them, please let me know.

**Comment by A11v1r15** [comment]
I just sent a [pull request](https://github.com/ricksouth/serilum-mc-mod-sources/pull/6) to Serilium, I hope he accepts or at least get the code modifications I did and commit them himself

**Comment by ricksouth** [comment]
Sorry it took me so long to get to. I also lost track of the PR when I moved to separate sources for each mod.

I have just uploaded version 8.1 of Just Mob Heads which adds compatibility with note blocks. Thank you @A11v1r15 for the work!
